#ifndef SECRETS_H
#define SECRETS_H

/* Wifi Password */
const char* WIFI_SSID = "SSID";
const char* WIFI_PASSWD = "PASSWORD";

const char AWS_API_CERT[] = \
"-----BEGIN CERTIFICATE-----\n" \
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n" \
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n" \
"-----END CERTIFICATE-----\n";


#endif